ClassicShellSrc/ClassicStartMenu/ClassicStartMenuDLL/MenuContainer.cpp

newer devices (as ThinkPad X1C6) support _lower power idle mode_ - a deeper sleep that does not report as `S1`, `S2` or `S3`, but as `S0` flag - available in `powerCaps.AcA0`
https://msdn.microsoft.com/en-us/library/windows/desktop/aa373215(v=vs.85).aspx

add powerCaps.AoAc for S0 (low power idle mode)

---

ClassicStartSrc/ClassicStartMenu/ClassicStartMenuDLL/MenuContainer.cpp

CMenuContainer object was not destroyed when Start Menu window was closed.
It was referenced by IFrameworkInputPane::AdviseWithHWND call (to be able
to receive input pane notifications). The problem was that dereferencing
(IFrameworkInputPane::Unadvise) was called from CMenuContainer destructor
that is called only when object's refcount goes to zero.
In previous Windows versions it somehow worked, because for some reason
CMenuContainer object was no longer referenced when its window was
destroyed.
Apparently there was some change in IFrameworkInputPane handling in recent
Windows builds (starting with 17692).
To fix the issue we have to call IFrameworkInputPane::Unadvise() when
CMenuContainer's window is about to be destroyed.

Fix for recent Windows Insider builds (#11)

---

ClassicStartSrc/ClassicStartSetup/BuildArchives.bat
ClassicStartSrc/ClassicStartSetup/BuildBinaries.bat
ClassicStartSrc/ClassicStartSetup/BuildInstaller.bat
ClassicStartSrc/ClassicStartSetup/CreateSourceIndex.bat
ClassicStartSrc/ClassicStartSetup/__MakeFinal.bat
ClassicStartSrc/ClassicStartSetup/__MakeFinalAllLanguages.bat
ClassicStartSrc/Version.props
appveyor.yml

- Add symbols to 7z archive (15MB vs 34MB)
- Don't create source package (obsolete)
- Less verbose output (removed unnecessary distracting messages)
- Remove unneeded install script
- Add source index to PDBs (so that exact sources are automatically fetched during debugging)
The output of `__MakeFinal.bat` now looks like this:
> Version: 4.4.102
> -- Compiling
> --- 64bit
> --- 32bit
> --- Adding source index to PDBs
> --- ADMX
> -- Building Installer (en)
> --- HTML help
> --- 32bit MSI
> --- 64bit MSI
> --- MSI Checksums
> --- Bootstrapper
> -- Creating symbols package
> -- Creating localization package

Build improvements

---

ClassicStartSrc/ClassicStartMenu/ClassicStartMenuDLL/MenuContainer.cpp
ClassicStartSrc/ClassicStartMenu/ClassicStartMenuDLL/MenuContainer.h

Fixed issue related to the cleanup of the accessibility COM objects that
may cause Explorer to crash.
Submitted by Ivo Beltchev.
Fixes #53

Cleanup of the accessibility COM objects (#53)

---

Src/Setup/Setup.cpp
Src/Setup/Setup.rc
Src/Setup/Setup.vcxproj
Src/Setup/Setup.vcxproj.filters
Src/Setup/SetupHelper/SetupHelper.cpp
Src/Setup/resource.h

- Remove warning about very old ClassicShell version
- Remove obsolete/unused stuff
- Try to terminate ClassicShell Start Menu (to make upgrade a bit easier)
Also fixes #72 along the way.

Setup improvements

---

Localization/ExplorerL10N.ini
Localization/StartMenuL10N.ini

- Little fix to Italian translation.
- Header changed.

Fix ITA trans

---

Src/StartMenu/StartMenuDLL/MenuContainer.cpp

Updated to read the registry and enable or disable the appropriate power menu buttons for lock, sleep and hibernate according to what the user has checked in control panel.

Code to check registry for Power Button user choice.

---

Src/StartMenu/StartMenuDLL/MenuContainer.cpp

Commit 1a5f62a added possibility to hide Lock/Sleep/Hibernate buttons if
they were disabled in system power settings.
Unfortunately this didn't work for Lock button.
To fix the behavior we have to add lock command to `g_StdOptions` array
and then all the checks introduced in 1a5f62a will apply properly.
#173

Fix Lock button hiding

---

Src/StartMenu/StartMenu.cpp

`Open-Shell` needs to adjust itself after OS upgrade. It seems that
`StartMenuHelper` registration is lost after such upgrade:
http://www.classicshell.net/forum/viewtopic.php?f=7&t=8082#p34821
To fix this registration, administrator rights are required (means user
interaction, UAC).
While this is acceptable in consumer environment, it is typically not
desired in business environment where users typically doesn't have
administrator rights.
This patch allows to run `Open-Shell` in silent upgrade mode that will:
* check if OS version changed (otherwise end immediately)
* perform OS upgrade tasks without any user interraction
Such mode can be then used to create scheduled task that will run this
silent upgrade check on every boot with system rights:
`schtasks /Create /RU "NT AUTHORITY\SYSTEM" …

Add support for silent OS upgrade task

---

Src/StartMenu/StartMenuDLL/DragDrop.cpp
Src/StartMenu/StartMenuDLL/MenuCommands.cpp
Src/StartMenu/StartMenuDLL/MenuContainer.cpp
Src/StartMenu/StartMenuDLL/MenuContainer.h
Src/StartMenu/StartMenuDLL/ProgramsTree.cpp
Src/StartMenu/StartMenuDLL/StartMenuDLL.cpp

In several cases we don't want menu(s) to close when an action on menu was
done. For example on drag-n-drop or menu item deletion (where confirmation
dialog is shown).
In such situations `s_bPreventClosing` was set to true (and then back to
false when closing was allowed again).
Though original code honored this variable only in certain situations and
typically (at least on Win10) menus were hidden/closed despite of it.
This patch changes the behavior and menus(s) are not closed when
`s_bPreventClosing` is set to true.
Basically now menu(s) stay visible until there is an action that changes
active window.
Following functionality was also removed because it is not needed now:
* CMenuContainer::HideTemp
* COwnerWindow::OnClear
WM_CLEAR was sent to the window only by already removed …

Don't close menu(s) on certain operations

---

Src/StartMenu/StartMenuDLL/DragDrop.cpp
Src/StartMenu/StartMenuDLL/MenuCommands.cpp

Delete confirmation dialog may be (partially) hidden behing start menu.
As a result the dialog may be not accessible because start menu(s) are
displayed as top-most windows.
Thus when executing menu command we will make menu(s) non-topmost. So that
other windows can be drawn on top of menu(s).
Fixes #257

Fix issue with confirmation dialog being blocked

---

Src/StartMenu/StartMenuDLL/Accessibility.cpp
Src/StartMenu/StartMenuDLL/ItemManager.cpp

When `Invert Metro icon color` is enabled `Open-Shell` needs to
distinguish full color icons from monochromatic ones.
Color icons are displayed normally. Monochromatic ones are displayed
inverted (original background becomes transparent and foreground will
get Metro accent color).
Metro icon is loaded from Metro app resources (usually PNG image) as
bitmap with premultiplied alpha channel.
This causes monochromatic image to essentially become grayscale (because
RGB values are multiplied with alpha channel value).
Function `DetectGrayscaleImage` is used to distinguish such images.
Unfortunatelly if original image is grayscale (such as new Windows
Terminal icon) it is recognized as monochromatic and thus inverted.
To prevent this we will take into account also alpha channel in …

Fix 'Invert Metro icon color' option for grayscale icons

---

README.md

I just tested file access with the latest nightly build and this is the correct path for translations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-shell/open-shell-menu/377)

Fix folder for translations

---

Src/Lib/ResourceHelper.cpp

Blind attempt to eliminate a crash which seems to occur when PremultiplyBitmap() is called after LoadImage() fails.
I'm hoping this might fix the issue reported here: https://github.com/Open-Shell/Open-Shell-Menu/issues/400
Note I haven't been able to test yet, as a) I don't have a build environment, and b) it can take several days/weeks to recreate the issue.

Add null check to PremultiplyBitmap()

---

Src/StartMenu/StartMenuDLL/SkinManager.cpp

This should allow skin customizations for 120DPI (125% scaling)
displays.
Fixes #458 .

Skin: Add more DPI options

---

Src/StartMenu/StartMenuDLL/ItemManager.cpp
Src/StartMenu/StartMenuDLL/ItemManager.h
Src/StartMenu/StartMenuDLL/JumpLists.cpp
Src/StartMenu/StartMenuDLL/LogManager.cpp
Src/StartMenu/StartMenuDLL/LogManager.h
Src/StartMenu/StartMenuDLL/MenuContainer.cpp
Src/StartMenu/StartMenuDLL/MetroLinkManager.cpp
Src/StartMenu/StartMenuDLL/MetroLinkManager.h

Task jump-list items for modern apps require special handling.
First of all they don't provide icon directly.
Icon location is stored in `PKEY_AppUserModel_DestListLogoUri` property.
And then has to be resolved for given application package.
Next, context menu of provided `IShellLink` item doesn't seem to be able
to start actual link target.
Thus we need to obtain context menu of target item.

Fix the handling of Jump lists for modern applications

---

Src/StartMenu/StartMenuDLL/ItemManager.cpp
Src/StartMenu/StartMenuDLL/ItemManager.h
Src/StartMenu/StartMenuDLL/MenuPaint.cpp

Some icons (modern settings, jump-list tasks) are monochrome, basically
they are defined just by alpha channel.
Thus they can be displayed in any color (white is default).
Since these icons are white by default, they look nice on dark
backgrounds. But they are not very visible on light backgrounds.
Thus the idea is to 'colorize' such icon using color of corresponding
text item. That way they will always have proper color.
Fixes #466.

Display monochrome icons using color of corresponding text item

---

Src/Skins/Metro/SkinDescription.txt

This should improve the right-hand spacing when icon frames are enabled, and right-hand icons are disabled. There shouldn't be any extra icon/text padding for Main2 when icons aren't enabled.

Metro skin right-hand alignment with Icon Frames

---

Src/StartMenu/StartMenuDLL/SettingsUI.cpp

This should allow for icons in the menu to scale better for higher DPI displays. Configurations above 250% will retain the sizes for 240DPI.
I believe the sizes should behave the same as the DPI options added for skins at https://github.com/Open-Shell/Open-Shell-Menu/pull/459.

Scale menu icons up to 250% (240 DPI)

---

Src/StartMenu/StartMenuDLL/MenuContainer.cpp

When using skin with a different second column icon size, all of the
icons in it would become blank.
Because m_bTwoColumns is set after AddStandardItems, it is still false
in the column break check. As a workaround, use the value it's assigned
later in InitWindowInternal instead.
Fix Open-Shell/Open-Shell-Menu#980

Fix corrupted icons in second column

---

Src/StartMenu/StartMenu.cpp

It will force Open-Shell to reload settings from registry.
Fixes #1157.

Add -reloadsettings command line switch

---

Src/StartMenu/StartMenuDLL/MenuContainer.cpp

Fix regression caused by b89aaed7854212926729aabb4a05d5b517cb5549.
https://github.com/Open-Shell/Open-Shell-Menu/pull/1088#issuecomment-1273959550
The original commit fixed a bug where the icons would not be generated for the second column's icon size. However, the bugged behavior had masked a discrepancy between the icons generated for the inlined submenus (inserted as buttons) in CMenuContainer::AddStandardItems and the drawing settings for them in MenuSkin::LoadSkin. Here are the snippets in order:
https://github.com/Open-Shell/Open-Shell-Menu/blob/e6b33a70e4230d30ceff2ccc4eaf7c3be271f456/Src/StartMenu/StartMenuDLL/MenuContainer.cpp#L1275-L1305
https://github.com/Open-Shell/Open-Shell-Menu/blob/e6b33a70e4230d30ceff2ccc4eaf7c3be271f456/Src/StartMenu/StartMenuDLL/SkinManager.cpp#L2932-L29 …

Restore Main_no_icons2 behavior for inline subitems

---

Src/Setup/Setup.cpp
Src/StartMenu/StartMenuDLL/SkinManager.cpp
Src/StartMenu/StartMenuDLL/StartMenuDLL.cpp

- Start menu keyboard hotkey fix for Win11 Insider (#1165)
- Properly scale default skin font according to DPI (#1110)
- Setup: Recognize also /h and /help parameters (#1278)

Improvements

---

Src/StartMenu/StartMenuDLL/SkinManager.cpp

Original fix introduced in 528d15 was not correct. The problem is that `SystemParametersInfo` uses DPI that current session started with.
We should use `SystemParametersInfoForDpi` (available since Win10 1607) that returns properly scaled font size.
Fixes #1110

Properly scale default skin font according to DPI (#1110)

---

Src/Setup/Setup.wxs

IE was deprecated long ago. There is no need to install Classic IE by default.
Users will be still able to install it if they want.

Setup: Don't install Classic IE by default

---

Src/StartMenu/StartMenuDLL/StartMenuDLL.cpp

Shift Aero button slightly when it is positioned in corner of any monitor (not just primary one).
Moreover this shift should be done only for top/bottom taskbar.

Fix Aero button alignment on multiple monitors (#1310)

---

Src/StartMenu/StartMenuDLL/MenuPaint.cpp

Use steady_clock with 1ms resolution instead of GetTickCount that has typical resolution 10-16ms. This should result in more smooth menu animations.

Improve menu animation timing

---

Src/Lib/Settings.cpp
Src/Lib/Settings.h
Src/StartMenu/StartMenuDLL/MenuContainer.cpp
Src/StartMenu/StartMenuDLL/MenuContainer.h
Src/StartMenu/StartMenuDLL/SettingsUI.cpp

- Separate taskbar icon for Open-Shell menu settings dialog
- Allow negative horizontal/vertical menu offsets (#1629)
- Fix checkboxes in settings dialog with custom themes (#1630)
- Fix search results overlapping (#1648)
- Display "Searching..." progress always

Various fixes

---

Src/StartMenu/StartMenuDLL/StartMenuDLL.cpp

It may happen that during `InitStartMenuDLL` execution some component posts a message that is then intercepted by (still active) `HookInject` that will call `InitStartMenuDLL` again (and everything will repeat).
To prevent such endless recursion during initialization, we will make sure that `InitStartMenuDLL` will be executed just once.

Avoid recursive Start menu initialization (#1675)

---

Src/ClassicExplorer/ExplorerBHO.cpp
Src/ClassicExplorer/SettingsUI.cpp

It was available only for Win7.
But it seems to work/help also on Win8/10.
Fixes #1885.

Make `FixFolderScroll` available in all Windows versions

---

Src/BUILDME.txt
Src/Setup/__MakeFinal.bat
Src/Setup/__MakeFinalAllLanguages.bat
Src/StartMenu/StartMenuDLL/StartMenuDLL.cpp

Windows 11 22H2 introduced new touch-optimized taskbar for devices with touch screen.
It seems that in this mode taskbar window size is bigger than actual taskbar on screen. There is region defined for the window that covers actually displayed portion of the window.
We should account for that region (if present) when obtaining taskbar window dimensions.
More info about how to enable/disable touch taskbar: https://www.elevenforum.com/t/turn-on-or-off-tablet-optimized-taskbar-in-windows-11.5133/

Fix start button/menu misalignment on touch-screen devices

---

Src/StartMenu/StartMenuHelper/ModernSettings.cpp

It seems that AllSystemSettings file name changed since 24H2. We will look for new file first and then fall-back to original one.
Fixes #2033.

ModernSettings: Use proper AllSystemSettings file on newer Win11
